name: billingWeb Maven Build

on:
  push:
    branches:
      - frontend
  pull_request:
    branches:
      - frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (billingWeb )
        working-directory: billingWeb
        run: mvn clean install
